on:
    issue_comment:
      types:
      - created
      contains: "/frinkiac "

jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    env:
      FRINKIAC_OUT: "![frinkiac](https://frinkiac.com/meme/S02E03/986988.jpg?lines=didn%27t%20find%20anything)"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Frinkiac
        run: |
          search_term=$(echo "${{ github.event.comment.body }}" | sed 's/^\/frinkiac //')
          pr_number=$(echo "${{ github.event.comment.html_url }}" | sed 's/.*\/pull\/\([0-9]\+\)#.*/\1/')
          pr_description_url="https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}"
          pr="$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s $pr_description_url)"
          body=$(echo "$pr" | jq -r '.body')
          title=$(echo "$pr" | jq -r '.title')
          new_body="$body\n\n$frinkiac"
          frinkiac=$(docker run mannionjames/frinkiac:latest "$title" "$search_term")
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" \
            -d "{\"body\":\"$body\n\n$frinkiac\"}"
