on:
  pull_request:
    types:
      - opened
      - reopened




jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    env:
      FRINKIAC_OUT: "![frinkiac](https://frinkiac.com/meme/S02E03/986988.jpg?lines=didn%27t%20find%20anything)"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Frinkiac
      
        run: |
          frinkiac=$(docker run mannionjames/frinkiac:latest "are you sure that's safe?" "just refactoring repayments module for the fun of it")
          PR_NUMBER=2
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
            -d "{\"body\":\"$frinkiac\"}"